POST localhost:8080/api/companies
Content-Type: application/json

{
  "name": "uzkassa",
  "tin": "306351564",
  "brand": "cdti",
  "addressDTO": {
    "regionId": 1,
    "districtId": 1,
    "street": "boz ko'cha"
  }
}
###
GET localhost:8080/api/branches/1
Content-Type: application/json

{
  "companyId": 1,
  "name": "uzkassa",
  "addressDTO": {
    "regionId":1,
    "street": "istoqlol",
    "districtId": 2
  }
}
###

POST localhost:8080/api/departments
Content-Type: application/json

{
  "branchId": 1,
  "name": "accounting"
}
###
POST localhost:8080/api/auths/registration
Content-Type: application/json

{
  "branchId": 1,
  "companyId": 1,
  "firstName": "komil",
  "lastName": "komilov",
  "email": "komil4455@gmail.com",
  "departmentId": 1,
  "positionId": 1,
  "password": "12345",
  "phoneNumber": "+998937877455",
  "role": "ROLE_OWNER"
}
####
POST localhost:8080/api/auths/authorization
Content-Type: application/json

{
  "password": "12345",
  "phone": "+998937877455"
}

####
POST localhost:8080/api/auths/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSwiOiIrOTk4OTM3ODc3NDU1Iiwicm9sZSI6IlJPTEVfT1dORVIiLCJ0b2tlblR5cGUiOiJyZWZyZXNoIiwic3ViIjoiKzk5ODkzNzg3NzQ1NSIsImlhdCI6MTczNTg5ODcyMywiZXhwIjoxNzM3MTk0NzIzfQ.vu8RimUihOX601lnxp3DpcPWVY5giP3zXwo8K0Q0FfpsjeHHhE-sUyuGgrnFnaouVrWR0_mPfyXjVWmNHaex2A"
}



###
GET localhost:8080/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSwiOiIrOTk4OTM3ODc3NDU1Iiwicm9sZSI6IlJPTEVfT1dORVIiLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJzdWIiOiIrOTk4OTM3ODc3NDU1IiwiaWF0IjoxNzM1ODk4NzIzLCJleHAiOjE3MzU5ODUxMjN9.VYR3W3ZfW_CmVVeyUxlvJRHcM1tiF38m36y5JKTSEj58AJS5pf9X-LQxTc6rC9cdFXwe3H0vjRl_jyur3a13Uw



{
  "employeeId": 4,
  "title": "masjid",
  "content": "asr oqish"
}

####
PATCH localhost:8080/api/employees/3
###
GET localhost:8080/api/token-stores

###
DELETE localhost:8080/api/token-stores/99892255222