POST localhost:8080/api/companies
Content-Type: application/json

{
  "name": "uzkassa",
  "tin": "306351564",
  "brand": "cdti",
  "addressDTO": {
    "regionId": 1,
    "districtId": 1,
    "street": "boz ko'cha"
  }
}
###
GET localhost:8080/api/branches/1
Content-Type: application/json

{
  "companyId": 1,
  "name": "uzkassa",
  "addressDTO": {
    "regionId":1,
    "street": "istoqlol",
    "districtId": 2
  }
}
###

POST localhost:8080/api/departments
Content-Type: application/json

{
  "branchId": 1,
  "name": "accounting"
}
###
POST localhost:8080/api/auths/registration
Content-Type: application/json

{
  "branchId": 1,
  "companyId": 1,
  "firstName": "joni",
  "lastName": "jorayev",
  "email": "joni4455@gmail.com",
  "departmentId": 1,
  "positionId": 1,
  "password": "12345",
  "phoneNumber": "+998937877403",
  "role": "ROLE_OWNER"
}
####
POST localhost:8080/api/auths/authorization
Content-Type: application/json

{
  "password": "12345",
  "phone": "+998995001122"
}

####
POST localhost:8080/api/auths/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSwiOiIrOTk4OTk1MDAxMTIyIiwicm9sZSI6IlJPTEVfT1dORVIiLCJ0b2tlblR5cGUiOiJyZWZyZXNoIiwic3ViIjoiKzk5ODk5NTAwMTEyMiIsImlhdCI6MTczNTg4MTY0MywiZXhwIjoxNzM1ODgyNzIzfQ.3tJXx69tMmUe-j0VudBKvIoVTPIG0IiISy7GBxJ4KhVbVb61EL3VgBjLWQysHMiWYy4wGmGCjwW6vY0lrhvbyg"
}



###
GET localhost:8080/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSwiOiIrOTk4OTk1MDAxMTIyIiwicm9sZSI6IlJPTEVfT1dORVIiLCJ0b2tlblR5cGUiOiJyZWZyZXNoIiwic3ViIjoiKzk5ODk5NTAwMTEyMiIsImlhdCI6MTczNTg4MTc1NCwiZXhwIjoxNzM1ODgyODM0fQ.c-YUTJi-3siQXnNy6owY-Rhel054wzYlBGKAo3TyH8DNSe-poZec5rVAbXFY17XOFz0FHpAi49YA_08OFo2A9A



{
  "employeeId": 4,
  "title": "masjid",
  "content": "asr oqish"
}

####
PATCH localhost:8080/api/employees/3
###
GET localhost:8080/api/token-stores