package org.example.constants;

public interface MyConstants {
    //employee
    String EMPLOYEE_QUEUE_NAME = "EMPLOYEE_QUEUE";
    String EMPLOYEE_QUEUE_EXCHANGE = "EMPLOYEE_EXCHANGE";
    String EMPLOYEE_QUEUE_ROUTING_KEY = "EMPLOYEE_ROUTING_KEY";

    //task
    String TASK_QUEUE_NAME = "TASK_QUEUE";
    String TASK_QUEUE_EXCHANGE = "TASK_QUEUE_EXCHANGE";
    String TASK_QUEUE_ROUTING_KEY = "TASK_QUEUE_ROUTING_KEY";

    //branch
    String BRANCH_QUEUE_NAME = "BRANCH_QUEUE";
    String BRANCH_QUEUE_EXCHANGE = "BRANCH_QUEUE_EXCHANGE";
    String BRANCH_QUEUE_ROUTING_KEY = "BRANCH_QUEUE_KEY";

    //company
    String COMPANY_QUEUE_NAME = "COMPANY_QUEUE_NAME";
    String COMPANY_QUEUE_EXCHANGE = "COMPANY_QUEUE_EXCHANGE";
    String COMPANY_QUEUE_ROUTING_KEY = "COMPANY_QUEUE_ROUTING_KEY";

}
