package org.example.constants;

public interface MyConstants {

    String EMPLOYEE_QUEUE_NAME = "EMPLOYEE_QUEUE";
    String EMPLOYEE_QUEUE_EXCHANGE = "EMPLOYEE_EXCHANGE";
    String EMPLOYEE_QUEUE_ROUTING_KEY = "EMPLOYEE_ROUTING_KEY";

    String TASK_QUEUE_NAME = "TASK_QUEUE";
    String TASK_QUEUE_EXCHANGE = "TASK_QUEUE_EXCHANGE";
    String TASK_QUEUE_ROUTING_KEY = "TASK_QUEUE_ROUTING_KEY";
}
